#!/bin/bash
#SBATCH --time=01:00:00
#SBATCH --mem=10000M
#SBATCH --partition=short-serial

dtstr=${1}
outdir_top=${2} 
idir_top=${3}
tmpdir=${4}
cachedir=${5}

python Global_GEO.py --outdir_top=$outdir_top --idir_top=$idir_top --tmpdir=$tmpdir --cachedir=$cachedir $dtstr

            
